import '../assets/styles/globals.css'
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
// import GlobalStyles from '@/assets/styles/GlobalStyles'
import StyledComponentsRegistry from '@/lib/registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Boilerplate with NextJs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={`${inter.className} text-xs text-gray-700`}>
        <Providers>
          <StyledComponentsRegistry>
            {/* <GlobalStyles /> */}
            <main className="min-h-screen flex flex-col justify-center items-center">
              {children}
            </main>
          </StyledComponentsRegistry>
        </Providers>
        <ToastContainer />
        <footer className="text-center p-2">By Intelindev</footer>
      </body>
    </html>
  )
}
